---
- hosts: ubuntu
  become: true
  tasks:

  - name: update repository (sudo apt update) and istall updates (sudo apt upgrade -y) on ubuntu
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

