---
- hosts: ubuntu
  become: true
  tasks:

  - name: update repository index for ubuntu (sudo apt update) then upgrade distribution files (sudo apt upgrade -y)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

