---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: test
  become: true
  tasks:

  - name: install apache and php
    tags: apache,apache2;ubuntu
    apt:
      name:
        -  apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"



