---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: test
  become: true
  tasks:

  - name: install apache and php
    tags: apache,apache2;ubuntu
    apt:
      name:
        -  apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy csagent to all ubuntu hosts
    copy:
      src: crowdstrike-installer-debian-9_10_11.deb
      dest: /home/itbdr/crowdstrike-installer-debian-9_10_11.deb
      owner: itbdr
      group: itbdr




