---
- hosts: all
  become: true
  pre_tasks:

  - name: create patcher user
    tags: always
    user:
      name: patcher
      groups: root

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: Update Debian-based Systems
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == 'Debian'

  - name: install vmware tools on each ubuntu guest
    apt:
      name:
        - open-vm-tools
        - open-vm-tools-desktop
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: allow ssh thru firewall
    command: sudo ufw allow openssh
    become: true
    when: ansible_distribution == "Ubuntu"

  - name: Configure the kernel to keep connections alive when enabling the firewall
    sysctl:
      name: net.netfilter.nf_conntrack_tcp_be_liberal
      value: 1
      state: present
      sysctl_set: yes
      reload: yes
    when: ansible_distribution == "Ubuntu"

  - name: Enable ufw
    ufw: state=enabled
    when: ansible_distribution == "Ubuntu"

  - name: copy csagent to all ubuntu hosts
    copy:
      src: crowdstrike-installer-debian-9_10_11.deb
      dest: /home/itbdr/crowdstrike-installer-debian-9_10_11.deb
      owner: itbdr
      group: itbdr

  - name: install csagent
    command: apt install /home/itbdr/crowdstrike-installer-debian-9_10_11.deb
    become: true
    when: ansible_distribution == "Ubuntu"

  - name: set csagent customer ID
    command: sudo /opt/CrowdStrike/falconctl -s -f --cid=4F9398DCB63F43ED8D3FE99CB242AE1D-75
    become: true
    when: ansible_distribution == "Ubuntu"

  - name: start the csagent if just installed
    command: systemctl start falcon-sensor
    become: true
    when: ansible_distribution == "Ubuntu"

  - name: install zabbix agent
    command: sudo apt install zabbix-agent
    become: true
    when: ansible_distribution == "Ubuntu"

  - name: start zabbix_agent
    command: sudo systemctl enable zabbix-agent
    become: true
    when: ansible_distribution == "Ubuntu"

  - name: set zabbix agent firewall port
    command: sudo ufw allow 10050/tcp
    become: true
    when: ansible_distribution == "Ubuntu"

- hosts: test
  become: true
  tasks:

  - name: install apache and php
    tags: apache,apache2;ubuntu
    apt:
      name:
        -  apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: veeam_proxy
  become: true
  tasks:

  -  name: set firewall ports for veeam proxy services
     command: sudo ufw allow 443,902,2500:3300,49152:65535/tcp 
     become: true

- hosts: veeam_repos
  become: true
  tasks:

  -  name: set firewall ports  for veeam repos
     command: sudo ufw allow 443,2500:3300,6162/tcp
     become: true
